### PR TITLE
Publish gem in new org/register

### PR DESCRIPTION
**Pull request by zmariscal-ut**
# Purpose
We want to migrate this gem is from Gemfury to Github packages

# Implementation
Add a GitHub workflow to publish to a new org and registery

# Demo
https://github.com/orgs/UserTestingEnterprise/packages/rubygems/package/voicebase-client-ruby

# Notifications
@jthom-ut 
@rbellido-ut

### CODE REVIEW

**Comment by jthom-ut** [comment]
I know that we are trying to take a hands off approach to a lot of this.. But is this one used at all? I only see it in one internal lib that I believe is unused.

**Comment by zmariscal-ut** [comment]
> I know that we are trying to take a hands off approach to a lot of this.. But is this one used at all? I only see it in one internal lib that I believe is unused.

@jthom-ut  This gem is [open](https://rubygems.org/gems/voicebase-client-ruby/) for the public to use. If/when we decided to stop using Gemfury it felt appropriate for it to have a new home. As far as our monolith, it still has a fair amout of code referencing "voicebase", though I believe it's been sunset as far as calling the API. I don't see the harm in doing some sheep shuffling until we retire the underlying voicebase code and properly remove the monolith from using this gem.

**Comment by boshranabaei** [comment]
Not sure why still receiving emails from this repository, while not able to see it on my list to exit

**Review by jthom-ut — APPROVED** [review]

**Review by amora-ut — APPROVED** [review]

**Comment by zmariscal-ut** [comment]
> Not sure why still receiving emails from this repository, while not able to see it on my list to exit

@boshranabaei Sorry you're running into this. If you go to the repo and click on the dropdown labeled "Watch" you can select "Ignore" and you won't receive any updates about this repo.

**Pull request merged**
